<?php /** @var T4webFormRenderer\Element $viewModel */ ?>
<?php $viewModel = $this->viewModel()->getCurrent(); ?>

<div class="form-group<?= ($viewModel->hasMessages()) ? ' has-error' : ''; ?>">
    <div class="checkbox">
        <label>
            <input type="checkbox" name="<?=$this->name ?>" value="<?=$viewModel->getData()?>">
            <?=$this->label ?>
        </label>
    </div>
    <?php if ($viewModel->hasMessages()): ?>
        <p class="help-block"><?=implode('<br/> ', $viewModel->getMessages());?></p>
    <?php endif; ?>
</div>