<?php /** @var T4webFormRenderer\Element $viewModel */ ?>
<?php $viewModel = $this->viewModel()->getCurrent(); ?>

<div class="form-group<?= ($viewModel->hasMessages()) ? ' has-error' : ''; ?>">
    <div class="radio">
        <?php foreach($this->labels as $value=>$label): ?>
            <label>
                <input type="radio" name="<?=$this->name ?>" class="form-control"
                       value="<?=$value?>"
                       <?= ($viewModel->getData() == $value) ? ' checked=""' : ''; ?>>
                <?=$label?>
            </label>
        <?php endforeach; ?>
    </div>
    <?php if ($viewModel->hasMessages()): ?>
        <p class="help-block"><?=implode('<br/> ', $viewModel->getMessages());?></p>
    <?php endif; ?>
</div>